// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using stock_quote_alert_repositorio.Contexto;

namespace stock_quote_alert.Migrations
{
    [DbContext(typeof(AcaoContext))]
    [Migration("20211106121550_TesteMigration")]
    partial class TesteMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.11");

            modelBuilder.Entity("stock_quote_alert.Models.Tabelas.Consultas", b =>
                {
                    b.Property<long>("IdConsulta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DtaExecucao")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("MercadoAberto")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NomeAcao")
                        .HasColumnType("TEXT");

                    b.Property<bool>("RetornouResultados")
                        .HasColumnType("INTEGER");

                    b.Property<double>("ValorApurado")
                        .HasColumnType("REAL");

                    b.HasKey("IdConsulta");

                    b.ToTable("Consultas");
                });

            modelBuilder.Entity("stock_quote_alert.Models.Tabelas.EnvioEmail", b =>
                {
                    b.Property<long>("IdEmail")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DtaEnvio")
                        .HasColumnType("TEXT");

                    b.Property<string>("EmailEnviado")
                        .HasColumnType("TEXT");

                    b.Property<long>("IdConsulta")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.Property<bool>("StatusEnviado")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TipoEnvio")
                        .HasMaxLength(1)
                        .HasColumnType("TEXT");

                    b.HasKey("IdEmail");

                    b.HasIndex("IdConsulta")
                        .IsUnique();

                    b.ToTable("EnvioEmail");
                });

            modelBuilder.Entity("stock_quote_alert.Models.Tabelas.EnvioEmail", b =>
                {
                    b.HasOne("stock_quote_alert.Models.Tabelas.Consultas", "Consulta")
                        .WithOne("Email")
                        .HasForeignKey("stock_quote_alert.Models.Tabelas.EnvioEmail", "IdConsulta");

                    b.Navigation("Consulta");
                });

            modelBuilder.Entity("stock_quote_alert.Models.Tabelas.Consultas", b =>
                {
                    b.Navigation("Email");
                });
#pragma warning restore 612, 618
        }
    }
}
